Module5 task1
htmlacademy-javascript/1859915-keksobooking-25 pull request #5
Opened 2022-03-09 17:30 UTC by iirinastepanova

2022-03-09 18:05 UTC, ademaro commented on js/data.js
> +      avatar: avatarNumber < 10 ? 'img/avatars/user' + '0' + avatarNumber + '.png' : 'img/avatars/user' + '0' + avatarNumber + '.png',
используй вместо конкатенации — шаблонные строки

2022-03-09 18:07 UTC, ademaro commented on js/data.js
> +      adress: `${lat} , ${lng}`,
address и пробел перед запятой — лишний)

2022-03-09 18:07 UTC, ademaro commented on js/util.js
> +  return elements[getRandomPositiveInteger(0, elements.length - 1)];
сделай в одну строку без слова return и фигурных скобок

2022-03-09 18:08 UTC, ademaro commented on js/main.js
> +import {similarOffers} from './data.js';
импортируй функцию и тут делай генерацию массива, данные не переносим между модулями

2022-03-09 18:09 UTC, ademaro requested changes
Давай чутка подправим и двинем дальше, пока открытым оставлю

2022-03-09 19:24 UTC, iirinastepanova commented on js/data.js
> +      avatar: avatarNumber < 10 ? 'img/avatars/user' + '0' + avatarNumber + '.png' : 'img/avatars/user' + '0' + avatarNumber + '.png',
Про скобки немного не поняла, как можно вынести

2022-03-10 10:54 UTC, ademaro commented on js/data.js
> +const MIN_LAT = 35.65
точку с запятой потеряли)

2022-03-10 10:56 UTC, ademaro commented on js/data.js
> +const MIN_LAT = 35.65
Вот так как вариант можем запаковать в перечисление:
```js
const Coords = {
  MIN_LAT: 35.65,
  MAX_LAT: 35.7,
  MIN_LNG: 139.7,
  MAX_LNG: 139.8,
  PRECISION: 5
}
```

2022-03-10 11:04 UTC, ademaro commented on js/util.js
> + function getRandomPositiveInteger (a, b) {
пустая строка не нужна и лишний пробел вначале перед функцией

2022-03-10 11:05 UTC, ademaro approved these changes
В целом всё очень круто, молодец, двигаем дальше, начинается самое интересное)

2022-03-10 11:05 UTC, merged